<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" />
    <PackageReference Include="ReactiveUI.WPF" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\JedPlotUtils.ScottPlot.WPF\JedPlotUtils.ScottPlot.WPF.csproj" />
    <ProjectReference Include="..\DemoData\DemoData.csproj" />
  </ItemGroup>

</Project>
