<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="HierarchyGrid.Definitions" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.SourceGenerators">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JedPlotUtils.ScottPlot\JedPlotUtils.ScottPlot.csproj" />
  </ItemGroup>

</Project>
