<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LanguageExt.Core" Version="4.4.9" />
    <PackageReference Include="ReactiveUI" Version="22.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\JedPlotUtils.ScottPlot\JedPlotUtils.ScottPlot.csproj" />
  </ItemGroup>
  
</Project>
