<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot.Avalonia" />
    <PackageReference Include="ReactiveUI.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JedPlotUtils.ScottPlot\JedPlotUtils.ScottPlot.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="TimeSeriesView.axaml.cs">
      <DependentUpon>TimeSeriesView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
